name: Compress

on:
  push:
    branches: [main]
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"

jobs:
  compress:
    runs-on: ubuntu-latest
    if: github.repository == 'yanglbme/redis-multi-programming-language-practice'
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Compress Images
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "[Automated] Optimize images" -a

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
