name: Sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'yanglbme/redis-multi-programming-language-practice'
    steps:
      - name: Sync to gitee.com
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:yanglbme/redis-multi-programming-language-practice.git
          destination-repo: git@gitee.com:yanglbme/redis-multi-programming-language-practice.git

      # - name: Build Gitee Pages
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     gitee-username: yanglbme
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     gitee-repo: yanglbme/redis-multi-programming-language-practice
      #     branch: main
